# Generated by Django 5.0.4 on 2024-05-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
